-- SELECT_INSERT_UPDATE_DELETE_TRUNCATE_KOMUTLARI --

SELECT ID,CUSTOMERNAME FROM CUSTOMERS
SELECT * FROM CUSTOMERS

INSERT INTO CUSTOMERS(CUSTOMERNAME,CITY,DISTRICT,BIRTHDAY,GENDER) VALUES ('Ýrem Sari','Ýstanbul','Üsküdar','1999-12-18','F')

UPDATE CUSTOMERS SET NATION ='US',AGE = 40
UPDATE CUSTOMERS SET NATION ='TR',AGE=DATEDIFF(YEAR,BIRTHDAY,GETDATE())

DELETE FROM CUSTOMERS

TRUNCATE TABLE CUSTOMERS

--------------------------------------------

-- WHERE_KOMUTU --

SELECT* FROM CUSTOMERS
WHERE AGE < 25
WHERE AGE > 25
WHERE AGE <> 25

WHERE AGE BETWEEN 30 AND 20

WHERE CUSTOMERNAME LIKE 'Ýrem%'
WHERE CUSTOMERNAME LIKE '%Ýrem'
WHERE CUSTOMERNAME LIKE '%Ýrem%'
WHERE CUSTOMERNAME NOT LIKE '%Ýrem%'

WHERE DISTRICT IN ('Üsküdar','Kadýköy')
WHERE NOT DISTRICT IN ('Üsküdar','Kadýköy')

UPDATE CUSTOMERS SET GENDER='F'
WHERE GENDER = 'K'
UPDATE CUSTOMERS SET GENDER='M'
WHERE GENDER = 'E'

DELETE FROM CUSTOMERS WHERE ID>15

--------------------------------------------

-- AND_OR_OPERATORLERI --

SELECT * FROM CUSTOMERS WHERE CITY ='Ýstanbul' AND DISTRICT='Beylikdüzü'
SELECT * FROM CUSTOMERS WHERE CITY='Ýstanbul' AND DISTRICT IN ('Beylikdüzü','Esenler') AND GENDER = 'M'
SELECT * FROM CUSTOMERS WHERE CITY ='Ýstanbul' AND GENDER='M' AND BIRTHDAY BETWEEN '19900101' AND '20000101'

SELECT * FROM CUSTOMERS WHERE CITY='Ýstanbul' OR CITY='Ýzmir'
SELECT * FROM CUSTOMERS WHERE CITY IN ('Ýstanbul','Ýzmir','Bursa')

SELECT * FROM CUSTOMERS WHERE NOT BIRTHDAY BETWEEN '19900101' AND '19981231'
SELECT * FROM CUSTOMERS WHERE BIRTHDAY <='19900101' OR BIRTHDAY >= '19981231'
 
--------------------------------------------

-- DISTINCT_KOMUTU --

SELECT DISTINCT CITY FROM CUSTOMERS
SELECT DISTINCT CITY,DISTRICT FROM CUSTOMERS WHERE CITY = 'Ýstanbul'
SELECT DISTINCT AGE FROM CUSTOMERS WHERE CITY = 'Ýstanbul'

--------------------------------------------

-- ORDER_BY_KOMUTU --

SELECT * FROM CUSTOMERS ORDER BY ID ASC
SELECT * FROM CUSTOMERS ORDER BY CUSTOMERNAME
SELECT * FROM CUSTOMERS ORDER BY CITY ASC, CUSTOMERNAME DESC
SELECT * FROM CUSTOMERS WHERE CITY =  'Ýstanbul' ORDER BY CUSTOMERNAME,DISTRICT

--------------------------------------------

-- TOP_KOMUTU --

SELECT TOP 100 * FROM CUSTOMERS
SELECT TOP 50 PERCENT * FROM CUSTOMERS

--------------------------------------------

-- AGGREGATE FUNCTIONS (SUM,MIN,MAX,AVG,COUNT) ---

SELECT COUNT(*) FROM SALES
SELECT MIN(AMOUNT) FROM SALES
SELECT MAX(AMOUNT) FROM SALES

SELECT MIN(AMOUNT),MAX(AMOUNT),COUNT(FICHENO),SUM(TOTALPRICE),AVG(TOTALPRICE) FROM SALES WHERE CITY = 'Adana'
SELECT MIN(AMOUNT),MAX(AMOUNT),COUNT(FICHENO),SUM(TOTALPRICE),AVG(TOTALPRICE) FROM SALES WHERE CITY = 'Ankara'
SELECT MIN(AMOUNT),MAX(AMOUNT),COUNT(FICHENO),SUM(TOTALPRICE),AVG(TOTALPRICE) FROM SALES WHERE CITY = 'Ýstanbul'

SELECT * FROM SALES ORDER BY TOTALPRICE

--------------------------------------------

-- GROUP_BY_KAVRAMI --

SELECT CITY, 
MIN(TOTALPRICE) AS MIN_PRICE,
MAX(TOTALPRICE) AS MAX_PRICE,
COUNT(FICHENO) AS ROW_COUNT,SUM(TOTALPRICE) TOTALPRICE,
AVG(TOTALPRICE) AVGPRICE 
FROM SALES GROUP BY CITY

SELECT TOP 10 CITY,SUM(TOTALPRICE) AS TOTAL_PRICE FROM SALES GROUP BY CITY ORDER BY SUM(TOTALPRICE) DESC

--------------------------------------------

-- GROUP_BY_2--

SELECT * FROM SALES WHERE CITY = 'ANKARA' AND DATE2= '20190101' ORDER BY DATE_

UPDATE SALES SET DATE2 = CONVERT(DATE,DATE_)

--------------------------------------------

-- GROUP_BY_3 --

SELECT CITY,DATE2,SUM(TOTALPRICE) AS TOTALPRICE FROM SALES
WHERE CITY ='ANKARA'
GROUP BY CITY,DATE2
ORDER BY DATE2

--------------------------------------------

-- GROUP_BY_4 --

SELECT DATE2,CITY,SUM(TOTALPRICE) TOTALPRICE FROM SALES 
WHERE DATE2='20190101'
GROUP BY DATE2,CITY
ORDER BY SUM(TOTALPRICE) DESC

--------------------------------------------

-- GROUP_BY_5 --

UPDATE SALES SET MONTHNAME_= '01.OCAK' WHERE DATEPART(MONTH,DATE2)=1
UPDATE SALES SET MONTHNAME_= '02.ÞUBAT' WHERE DATEPART(MONTH,DATE2)=2
UPDATE SALES SET MONTHNAME_= '03.MART' WHERE DATEPART(MONTH,DATE2)=3
UPDATE SALES SET MONTHNAME_= '04.NÝSAN' WHERE DATEPART(MONTH,DATE2)=4
UPDATE SALES SET MONTHNAME_= '05.MAYIS' WHERE DATEPART(MONTH,DATE2)=5
UPDATE SALES SET MONTHNAME_= '06.HAZÝRAN' WHERE DATEPART(MONTH,DATE2)=6
UPDATE SALES SET MONTHNAME_= '07.TEMMUZ' WHERE DATEPART(MONTH,DATE2)=7
UPDATE SALES SET MONTHNAME_= '08.AÐUSTOS' WHERE DATEPART(MONTH,DATE2)=8
UPDATE SALES SET MONTHNAME_= '09.EYLÜL' WHERE DATEPART(MONTH,DATE2)=9
UPDATE SALES SET MONTHNAME_= '10.EKÝM' WHERE DATEPART(MONTH,DATE2)=10
UPDATE SALES SET MONTHNAME_= '11.KASIM' WHERE DATEPART(MONTH,DATE2)=11
UPDATE SALES SET MONTHNAME_= '12.ARALIK' WHERE DATEPART(MONTH,DATE2)=12

SELECT TOP 80 CITY,MONTHNAME_,SUM(TOTALPRICE) AS TOTALPRICE FROM SALES
GROUP BY CITY,MONTHNAME_
ORDER BY CITY,MONTHNAME_

SELECT MONTHNAME_,CITY,SUM(TOTALPRICE) AS TOTALPRICE FROM SALES
GROUP BY CITY,MONTHNAME_
ORDER BY MONTHNAME_,SUM(TOTALPRICE) DESC

--------------------------------------------

-- GROUP_BY_6 --

SELECT CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4,
SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(*) AS ROWCOUNT_,
SUM(AMOUNT) AS TOTALAMOUNT FROM SALES
GROUP BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4
ORDER BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4

--------------------------------------------

-- GROUP_BY_7 --

SELECT CITY,COUNT(DISTINCT FICHENO) AS CUSTOMERNUMBER FROM SALES
GROUP BY CITY
ORDER BY CITY

SELECT CITY,MONTHNAME_,COUNT(DISTINCT FICHENO) AS CUSTOMERNUMBER FROM SALES
GROUP BY CITY,MONTHNAME_
ORDER BY CITY,MONTHNAME_

SELECT CITY,COUNT(DISTINCT CUSTOMERNAME) AS UNIQUECUSTOMER,
COUNT(DISTINCT FICHENO) AS CUSTOMERNUMBER, COUNT(*) ITEMNUMBER FROM SALES
GROUP BY CITY
ORDER BY CITY

--------------------------------------------

-- GROUP_BY_8 --

SELECT CITY,SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(DISTINCT CUSTOMERNAME) CUSTOMERNUMBER FROM SALES
GROUP BY CITY
HAVING SUM(TOTALPRICE) > 40000
ORDER BY SUM(TOTALPRICE) DESC

SELECT CITY,SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(DISTINCT CUSTOMERNAME) CUSTOMERNUMBER FROM SALES
GROUP BY CITY
HAVING COUNT(DISTINCT CUSTOMERNAME) > 2000
ORDER BY SUM(TOTALPRICE) DESC

--------------------------------------------

-- RDMS_WITH_SCRIPT --

CREATE TABLE TEST(
ID INT IDENTITY(1,1),
CUSTOMERNAME VARCHAR(60),
CONSTRAINT [PK_TEST] PRIMARY KEY CLUSTERED(ID ASC)
)

DROP TABLE TEST

--------------------------------------------

-- TABLO_BIRLESTIRME --

SELECT USERS.*,ADDRESS.ADDRESSTEXT FROM USERS,ADDRESS
WHERE USERS.ID = ADDRESS.USERID
AND USERS.ID = 1

--------------------------------------------

-- ALIAS_KULLANIMI --

SELECT U.NAMESURNAME AS ADSOYAD,U.EMAIL MAILADRESI,U.GENDER CINSIYET,U.BIRTHDATE DOGUMTARIHI,A.ADDRESSTEXT ACIKADRES,A.*
FROM USERS U, ADDRESS A
WHERE U.ID = A.USERID AND U.ID =4

UPDATE USERS SET BIRTHDATE = '19930121' WHERE NAMESURNAME = 'Emirhan SELÝM'

--------------------------------------------

-- 2_DEN_FAZLA_TABLO_KULLANIMI --

SELECT U.NAMESURNAME ADSOYAD,U.EMAIL MAILADRESI, U.GENDER CINSIYET,
A.ADDRESSTEXT ACIKADRES,
A.POSTALCODE POSTAKODU,
C.COUNTRY ULKE,
CT.CITY SEHIR,
T.TOWN ILCE,
D.DISTRICT SEMT FROM
USERS U, ADDRESS A, CITIES CT, COUNTRIES C, TOWNS T, DISTRICTS D
WHERE U.ID = A.USERID AND C.ID= A.COUNTRYID AND CT.ID = A.CITYID AND T.ID = A.TOWNID AND D.ID = A.DISTRICTID
AND CT.CITY LIKE 'Bursa'
ORDER BY U.NAMESURNAME

--------------------------------------------

-- AGGREGATE_FUNC_WITH_RD --

SELECT CT.CITY SEHIR,COUNT(U.ID) KULLANICISAYISI,COUNT(DISTINCT T.TOWN) ILCE FROM
ADDRESS A,CITIES CT,COUNTRIES C,DISTRICTS D,	USERS U,TOWNS T
WHERE U.ID = A.USERID AND C.ID = A.COUNTRYID AND CT.ID = A.CITYID AND D.ID = A.DISTRICTID AND T.ID = A.TOWNID
GROUP BY CT.CITY

SELECT U.NAMESURNAME KULLANICIADI ,COUNT(DISTINCT C.ID) SEHIR,COUNT(DISTINCT T.TOWN) ILCE FROM
ADDRESS A,CITIES CT,COUNTRIES C,DISTRICTS D,	USERS U,TOWNS T
WHERE U.ID = A.USERID AND C.ID = A.COUNTRYID AND CT.ID = A.CITYID AND D.ID = A.DISTRICTID AND T.ID = A.TOWNID
GROUP BY U.NAMESURNAME
HAVING COUNT(DISTINCT T.TOWN) > 2

--------------------------------------------

-- JOIN KULLANIMI --

SELECT U.NAMESURNAME,U.EMAIL,C.COUNTRY,CT.CITY,T.TOWN,D.DISTRICT,A.ADDRESSTEXT
FROM USERS U
JOIN ADDRESS A ON A.USERID = U.ID
JOIN COUNTRIES C ON C.ID = A.COUNTRYID
JOIN CITIES CT ON CT.ID = A.CITYID
JOIN TOWNS T ON T.ID = A.TOWNID
JOIN DISTRICTS D ON D.ID = A.DISTRICTID

SELECT CT.CITY,COUNT(U.ID) AS KULLANICISAYISI
FROM USERS U
JOIN ADDRESS A ON A.USERID = U.ID
JOIN COUNTRIES C ON C.ID = A.COUNTRYID
JOIN CITIES CT ON CT.ID = A.CITYID
JOIN TOWNS T ON T.ID = A.TOWNID
JOIN DISTRICTS D ON D.ID = A.DISTRICTID
GROUP BY CT.CITY

--------------------------------------------

-- JOIN_TURLERI --

CREATE TABLE USERS(
	ID INT IDENTITY(1,1) NOT NULL, USERNAME_ VARCHAR(50)NULL
CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED(ID ASC))

CREATE TABLE ADDRESS(
	ID INT IDENTITY(1,1)NOT NULL, USERID INT NULL , ADDRESSTEXT VARCHAR (100) NULL
CONSTRAINT [PK_ADDRESS] PRIMARY KEY CLUSTERED(ID ASC))



SELECT U.ID,U.USERNAME_,A.ADDRESSTEXT FROM USERS U
JOIN ADDRESS A ON A.USERID = U.ID

SELECT U.ID,U.USERNAME_,A.ADDRESSTEXT FROM USERS U
INNER JOIN ADDRESS A ON A.USERID = U.ID

SELECT U.ID,U.USERNAME_,A.ADDRESSTEXT FROM USERS U
LEFT JOIN ADDRESS A ON A.USERID = U.ID

SELECT U.ID,U.USERNAME_,A.ADDRESSTEXT FROM USERS U
RIGHT JOIN ADDRESS A ON A.USERID = U.ID

SELECT U.ID,U.USERNAME_,A.ADDRESSTEXT FROM USERS U
FULL JOIN ADDRESS A ON A.USERID = U.ID

--------------------------------------------

-- CASE_WHEN --

SELECT DATEPART(YEAR,DATE_) YIL,
DATEPART(MONTH,DATE_) AY,
CASE
	WHEN PAYMENTTYPE = 1 THEN 'Kredi Kartý'
	WHEN PAYMENTTYPE = 2 THEN 'Havale'
END AS ODEMETURU_ACIKLAMA,
SUM(PAYMENTTOTAL) AS TOPLAMTUTAR
FROM PAYMENTS

GROUP BY DATEPART(YEAR,DATE_),DATEPART(MONTH,DATE_)
ORDER BY DATEPART(YEAR,DATE_),DATEPART(MONTH,DATE_)

--------------------------------------------

-- SUBQUERY --

SELECT U.*,
(SELECT TOP 1 ADDRESSTEXT FROM ADDRESS WHERE USERID = U.ID ORDER BY ID DESC) SONADRES
(SELECT TOP1 ADDRESSTEXT FROM ADDRESS WHERE USERID =U.ID ORDER BY ID) ILKADRES
(SELECT COUNT(ADDRESSTEXT) FROM ADDRESS WHERE USERID = I.ID) ADRESSAYISI
FROM USERS U

--------------------------------------------

-- STRINGISLEMLERI --

-- ASCII_CHAR --
ASCII('A') -- DEGERI ASCII'YE CEVIRIR
CHAR(65) -- DEGERI ASCII'DEN KARAKTERE CEVIRIR

-- SUBSTRING --
SUBSTRING('UTKU TUNCABAYIN',1,4) -- IFADEYI ISTENILEN YERDEN ALIR

-- CHARINDEX --
CHARINDEX('U','UTKU TUNCABAYIN',1) -- IFADENIN BULUNDUGU INDEXI VERIR

-- CONCAT --
CONCAT('UTKU','TUNCABAYIN') -- IFADELERI BIRLESTIRIR
CONCAT_WS(' ','UTKU','TUNCABAYIN') -- IFADELERI BOSLUKLU BIRLESTIRIR

-- FORMAT --
FORMAT(GETDATE(),'d','en-us') -- IFADEYI ISTENILEN SEKILDE GOSTERIR

-- LEFT_RIGHT_LEN --
LEFT('UTKU TUNCABAYIN',4) -- SOLDAN ISTENILEN SAYIDA KARAKTERI VERIR
RIGHT('UTKU TUNCABAYIN',10) -- SAGDAN ISTENILEN SAYIDA KARAKTERI VERIR
LEN('UTKU') -- IFADENIN UZUNLUGUNU VERIR

--TRIM_LTRIM_RTRIM --
TRIM(' UTKU TUNCABAYIN ') -- BOSLUKLARI TEMIZLER
LTRIM(' UTKU TUNCABAYIN ') -- SOLDAKI BOSLUKLARI TEMIZLER
RTRIM(' UTKU TUNCABAYIN ') -- DAGDAKI BOSLUKLARI TEMIZLER

-- LOWER_UPPER_REVERSE_REPLICATE --
LOWER('UTKU') -- IFADEYI KUCUK HARF YAPAR
UPPER('UTKU') -- IFADEYI BUYUK HARF YAPAR
REVERSE('UTKU') -- IFADEYI TERS CEVIRIR
REPLICATE('UTKU',2) -- IFADEYI ISTENILEN KADAR KOPYALAR

-- REPLACE --
REPLACE('UTKU TUNCABAYIN','UTKU','UTKUT') --IFADENIN ISTENILEN KISMINI DEGISTIRIR

-- OTHER --
GETDATE()
DATEPART()
CONVERT()